import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../../domain/entities/shader_params.dart';
import '../../domain/entities/shader_spec.dart';
import '../rendering/shader_program_cache.dart';

/// Puts a shader's GLSL source and its Dart wiring on the clipboard.
///
/// This is the feature that turns the app from a demo into a deliverable.
/// A client who sees it says "so you could send me this" — and yes, that's
/// exactly what it does. Thirty lines of Dart, and it's the highest-value
/// thing in the build after the shaders themselves.
///
/// The wiring block bakes in the *current* param values rather than the
/// defaults, so what you copy is what you were looking at when you hit
/// the button.
abstract final class ShaderExporter {
  static Future<void> copy(
    BuildContext context,
    ShaderSpec spec,
    ShaderParams params,
  ) async {
    final buffer = StringBuffer()
      ..writeln('// ${spec.name}')
      ..writeln('// ${spec.assetPath}')
      ..writeln('// Generated by Aurora')
      ..writeln()
      ..writeln(_source(spec.id))
      ..writeln()
      ..writeln(_wiringBlock(spec, params));

    await Clipboard.setData(ClipboardData(text: buffer.toString()));

    if (!context.mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Shader and wiring copied'),
        duration: Duration(seconds: 2),
      ),
    );
  }

  static String _source(String id) {
    final source = ShaderProgramCache.source(id);
    return source.isEmpty
        // Should never happen once warm-up succeeds, but a cryptic
        // empty clipboard is worse than a note explaining why.
        ? '// GLSL source unavailable — was the shader warmed up?'
        : source;
  }

  static String _wiringBlock(ShaderSpec spec, ShaderParams p) =>
      '''
// ─────────────────────────────────────────────────────────────────
// Add to pubspec.yaml:
//
//   flutter:
//     shaders:
//       - ${spec.assetPath}
//
// Then in Dart:
// ─────────────────────────────────────────────────────────────────

final shader = FragmentProgram.fromAsset('${spec.assetPath}')
    .fragmentShader();

// Uniform slots are positional. vec2 consumes 2, vec3 consumes 3.
shader.setFloat(0, size.width);   // uSize.x
shader.setFloat(1, size.height);  // uSize.y
shader.setFloat(2, time);         // uTime
shader.setFloat(3, ${p.speed});   // uSpeed
shader.setFloat(4, ${p.intensity}); // uIntensity
shader.setFloat(5, ${p.colorA.r}); // uColorA.r
shader.setFloat(6, ${p.colorA.g}); // uColorA.g
shader.setFloat(7, ${p.colorA.b}); // uColorA.b
shader.setFloat(8, ${p.colorB.r}); // uColorB.r
shader.setFloat(9, ${p.colorB.g}); // uColorB.g
shader.setFloat(10, ${p.colorB.b}); // uColorB.b

canvas.drawRect(Offset.zero & size, Paint()..shader = shader);
''';
}
